[[objects]]
x = 0
y = 300
width = 1200
height = 60

[[objects]]
x = 300
y = 240
width = 100
height = 20

[[objects]]
x = 500
y = 180
width = 100
height = 20

[[objects]]
x = 1300
y = 250
width = 200
height = 50